# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadSecureFile@1
  displayName: 'Download JMeter script'
  inputs:
    secureFile: 'My_Azure_Test.jmx'

- script: |
    echo "Executing JMeter test..."
    jmeter -n -t $(Agent.TempDirectory)/My_Azure_Test.jmx -l $(Build.ArtifactStagingDirectory)/testresults.jtl
  displayName: 'Run JMeter tests'

- task: PublishTestResults@2
  displayName: 'Publish test results'
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/testresults.jtl'
    searchFolder: '$(Build.ArtifactStagingDirectory)'
