# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

execution:
- executor: jmeter
  concurrency: 10
  hold-for: 1m
  ramp-up: 10s
  scenario: sample test
scenarios:
  sample test:
    script: My_Azure_Test.jmx
